# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: AthenaAnnounce # jekyll-seo-tag > Owners twitter username
author: Taylor Salo # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/Miami # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: # The post list page content
    feature_text:
    feature_image: "https://unsplash.it/1300/400?image=1067"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "ATHENA" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/images/logo.png" # Site logo, also used in jekyll-seo-tag
description: "ATHENA is a tool for classifying cognitive neuroscience studies according to the Cognitive Paradigm Ontology (CogPO)." # Site description and default description, also used in jekyll-seo-tag
url: "https://tsalo.github.io/athena-web" # Site url, also used in jekyll-seo-tag
baseurl:
repo: "https://github.com/tsalo/athena-web"
email: "tsalo006@fiu.edu"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account

# 8. Site navigation
navigation_header:
  Home: /
  People: /people/
  Publications: /publications/

navigation_footer:
  ATHENA NSF: "https://www.nsf.gov/awardsearch/showAward?AWD_ID=1631325"

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  GitHub: https://github.com/AthenaSTM
  Twitter: https://twitter.com/athenaannounce

sharing_links:
    #Twitter:
